$font = 3270 Nerd Font
$text_red = rgba(255, 85, 85, 1.0)
$font_size = 24

# i, j | x, y

general {
    hide_cursor = false
}

# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = ~/Wallpapers/DS_lock.png
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 1)
    outer_color = rgba(255, 85, 85, 1.0)

    check_color = rgba(93, 93, 93, 0.5)
    fail_color = rgba(255, 85, 85, 1.0)

    fade_on_empty = false
    rounding = 15

    font_color = rgba(255, 85, 85, 1.0)
    font_family = $font
    placeholder_text = Convergence has started...
    fail_text = YOU DIED

    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # hide_input = true

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = $font
    color = $text_red

    position = -30, 0
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A | %B %d, %Y" # update every 60 seconds
    font_color = rgba(255, 85, 85, 1.0)
    font_size = 25
    font_family = $font
    color = $text_red

    position = -30, -150
    halign = right
    valign = top
}

label {
    monitor =
    text = Make us whole again.
    font_size = $font_size
    font_family = $font
    color = $text_red
    
    position = 0, 30
    halign = center
    valign = center
}
