### Binds ###
set -g prefix C-s
unbind C-b
bind-key C-s send-prefix

unbind r
bind r source-file ~/.tmux.conf

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind -r m resize-pane -Z

### Pluggins ###
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"

### Other Settings ###
set -g mode-keys vi
set -g mouse on
set -g focus-events on
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Tc'
set -g base-index 1
set -g renumber-windows 1
set -g @resurrect-capture-pane-contents "on"
set -g @continuum-restore "on"

### Status Bar(s) ###
set-option -g status-position top
set -g status-style "bg=#3c3836,fg=#a89984"
set -g status-left "#[bg=#fb4934,fg=#3c3836]   #{session_name} #[bg=#fe8019,fg=#fb4934]#[bg=#fe8019,fg=#282828]#{?client_prefix, PREFIX ,}#[bg=#504945,fg=#fe8019]"
set -g status-left-length 500
set -g window-status-format "#[bg=#504945] #{window_index}-#{window_name} #{?#{==:#{window_index},#{last_window_index}},#[bg=#3c3836 fg=#504945],}"
set -g window-status-current-format "#[bg=#a89984,fg=#504945]#[fg=#282828] #{window_index}-#{window_name} #[bg=#504945,fg=#a89984]#{?#{==:#{window_index},#{last_window_index}},#[bg=#3c3836],}"
set -g window-status-separator ""
set -g status-right ""
### Removed right side of status bar ###
#(pwd) #[fg=#504945]#[bg=#504945,fg=#a89984] #(whoami)  #[bg=#a89984,fg=#282828] #{host_short} 󰣇  \
#[bg=#a89984,fg=#fe8019]#[bg=#fe8019,fg=#3c3836] #(date +%a-%b-%d) #[fg=#fb4934]#[bg=#fb4934,fg=#3c3836] #(date +%H:%M) "
set -g status-right-length 500
set -g status-interval 1

### Panes ###
set -g pane-base-index 1
set -g pane-border-format "#{?pane_active,\
╡#[fg=#3c3836 bg=#fe8019]  #{pane_index}-#{pane_current_command}  #[fg=#fe8019 bg=default]╞,\
╡#[fg=#fe8019 bg=default]  #{pane_index}-#{pane_current_command}  #[fg=#fe8019]╞}"
set -g pane-border-lines double
set -g pane-border-status 'top'
set -g pane-border-style fg=#fe8019
set -g pane-active-border-style fg=#fe8019

run '~/.tmux/plugins/tpm/tpm'
